spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    driver: mysql
    url: r2dbc:mysql://localhost:3306/commerce?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: rkdudmysql4_
    pool:
      enabled: false