spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    driver: mysql
    url: r2dbc:mysql://localhost:3307/commerce?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: rkdudmysql4_
    pool:
      enabled: false
graphql:
  servlet:
    enabled: true
    mapping: /graphql
  altair:
    enabled: true
    mapping: /altair
    subscriptions:
      timeout: 30
      reconnect: false
    static:
      base-path: /
    page-title: Altair
    options:
      endpoint-url: /graphql